### ISSUE TITLE
gilc for multi DOF robot manipulator

### ISSUE THREAD

**Issue by TBetterman** [meco-group/gilc#2]
Hi, the examples list in this project blongs to low dim case, i want consult whether gilc can apply to multi dim case, such as 6-DOF robot manipulator? Is there some examples that use gilc for robot manipulator control? I am really in trouble when apply it to robot manipulator.

Thanks!

**Comment by asteinh** [comment]
Generally speaking, the framework can accommodate pretty much any dynamics (see e.g. [this publication](https://www.researchgate.net/publication/326152123_An_Efficient_Iterative_Learning_Approach_to_Time-optimal_Path_Tracking_for_Industrial_Robots), where we apply it to a 6-DOF manipulator to trade-off between tracking performance and a time-optimal solution).

Due to the complexity of the dynamics, we don't have any examples for such a high-dimensional case - an extension should be straight forward. However, the solution of the NLP(s) resulting from using such a model is anything but predictable, depending on a number of properties (e.g. model parameters, chosen reference, etc.).

There's two ways to get help on this:
- Either you provide a minimal working example, based on which we can have a look at what's going wrong.
- Or (in case you don't want to share your problem details publicly) you can get in touch [via e-mail](https://www.mech.kuleuven.be/en/pma/research/meco/people/00102655).

Note, however, that without more information (i.e., details on the problem you're trying to solve) we won't be able to do much.

**Comment by TBetterman** [comment]
> Generally speaking, the framework can accommodate pretty much any dynamics (see e.g. [this publication](https://www.researchgate.net/publication/326152123_An_Efficient_Iterative_Learning_Approach_to_Time-optimal_Path_Tracking_for_Industrial_Robots), where we apply it to a 6-DOF manipulator to trade-off between tracking performance and a time-optimal solution).
> 
> Due to the complexity of the dynamics, we don't have any examples for such a high-dimensional case - an extension should be straight forward. However, the solution of the NLP(s) resulting from using such a model is anything but predictable, depending on a number of properties (e.g. model parameters, chosen reference, etc.).
> 
> There's two ways to get help on this:
> 
> * Either you provide a minimal working example, based on which we can have a look at what's going wrong.
> * Or (in case you don't want to share your problem details publicly) you can get in touch [via e-mail](https://www.mech.kuleuven.be/en/pma/research/meco/people/00102655).
> 
> Note, however, that without more information (i.e., details on the problem you're trying to solve) we won't be able to do much.

Thank you for your reply. I have read the paper you mentioned. I would like to ask, if i want to apply gilc to the multi-degree-of-freedom manipulator, must i need to establish the discrete state equation of the manipulator? like(the example provided in the project):
![image](https://user-images.githubusercontent.com/12430411/69495154-c6528400-0efe-11ea-958e-d7d81f797a92.png)

In addition, for this project, I have a question: if I use another controlled system, do I only need to create a new system model like invpen.py and then reset the parameters such as the number of state variables? Besides these, what else needs to be modified? Such as plant.py.

Finally, I would like to ask if there are any examples that can be applied to the higher-order system, any higher-order system is ok. In this way, I may refer to the example and modify it, and finally apply it to my five-degree-of-freedom universal robot

**Comment by TBetterman** [comment]
I just checked your personal page and found that I have read a lot of your articles which have given me a lot of help。Thanks a lot

**Comment by asteinh** [comment]
> I would like to ask, if i want to apply gilc to the multi-degree-of-freedom manipulator, must i need to establish the discrete state equation of the manipulator?

Yes, gILC requires a discretized state-space model to be available (the same way it appears in the code snippet you included).

> if I use another controlled system, do I only need to create a new system model like invpen.py and then reset the parameters such as the number of state variables? Besides these, what else needs to be modified? Such as plant.py.

Yes, you would change `invpen.py` according to your system (for a 6DOF robot you would get a right-hand side `f` with `nx = 12` entries, etc.).
`plant.py` should be generic enough to accommodate your manipulator dynamics, so this code *won't require* changes. Once you have adapted `invpen.py` you can call e.g. its inherited `sim()` function and you'll be able to simulate your plant.

> Finally, I would like to ask if there are any examples that can be applied to the higher-order system, any higher-order system is ok. In this way, I may refer to the example and modify it, and finally apply it to my five-degree-of-freedom universal robot

As mentioned above, we don't have any examples with higher-order dynamics available (due to the complexity). However, you are welcome to share your problem/model one way or another, such that we can try to help with your specific issue.

**Comment by TBetterman** [comment]
> > I would like to ask, if i want to apply gilc to the multi-degree-of-freedom manipulator, must i need to establish the discrete state equation of the manipulator?
> 
> Yes, gILC requires a discretized state-space model to be available (the same way it appears in the code snippet you included).
> 
> > if I use another controlled system, do I only need to create a new system model like invpen.py and then reset the parameters such as the number of state variables? Besides these, what else needs to be modified? Such as plant.py.
> 
> Yes, you would change `invpen.py` according to your system (for a 6DOF robot you would get a right-hand side `f` with `nx = 12` entries, etc.).
> `plant.py` should be generic enough to accommodate your manipulator dynamics, so this code _won't require_ changes. Once you have adapted `invpen.py` you can call e.g. its inherited `sim()` function and you'll be able to simulate your plant.
> 
> > Finally, I would like to ask if there are any examples that can be applied to the higher-order system, any higher-order system is ok. In this way, I may refer to the example and modify it, and finally apply it to my five-degree-of-freedom universal robot
> 
> As mentioned above, we don't have any examples with higher-order dynamics available (due to the complexity). However, you are welcome to share your problem/model one way or another, such that we can try to help with your specific issue.

Maybe my question is stupid. I am new to robotic arm. I want to ask how to get the discrete state equation of the robotic arm. All I see are forward and inverse kinematics analysis of the robotic arm

**Comment by asteinh** [comment]
This question seems beyond the scope of gILC and the issue tracker :wink: 

You can find good introductions to modelling of dynamics either online (e.g. [this PDF](https://www.cds.caltech.edu/~murray/books/MLS/pdf/mls94-manipdyn_v1_2.pdf)) or in many robotics books. All you need is the dynamics, which you discretize and then (in the case of a manipulator, most likely) choose joint angles and velocities as the states.

**Comment by TBetterman** [comment]
> This question seems beyond the scope of gILC and the issue tracker 😉
> 
> You can find good introductions to modelling of dynamics either online (e.g. [this PDF](https://www.cds.caltech.edu/~murray/books/MLS/pdf/mls94-manipdyn_v1_2.pdf)) or in many robotics books. All you need is the dynamics, which you discretize and then (in the case of a manipulator, most likely) choose joint angles and velocities as the states.

you are so nice~
Thanks a lot!
